
// app
export const APP_START_UP_COMPLETE = 'APP_START_UP_COMPLETE';
export const SET_CONTENT_OF_CONFIRM_MODAL = 'SET_CONTENT_OF_CONFIRM_MODAL';

// user
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';
